angryexception/__init__.py,sha256=DcZSNexXIgqp4XAthqHIBUAwUIjZ_TeRs3LrtrKh58s,1018
angryexception-1.0.1.dist-info/WHEEL,sha256=y3eDiaFVSNTPbgzfNn0nYn5tEn1cX6WrdetDlQM4xWw,83
angryexception-1.0.1.dist-info/METADATA,sha256=rkkbhyky0wrPnm72fwhmZiZhWGlSdHw2gMv65F2JAI4,886
angryexception-1.0.1.dist-info/RECORD,,
